.\"encode man page for CSCI 241
.\" Eva Fineberg and Ruby Boyd  - Fall 2014 

.TH encode_man 1 "November 2014" "CSCI 241" "Oberlin College" 

.SH NAME
.B encode
\- input of text file and a specified file to write to (optional) 

.SH SYNOPSIS
.B encode
<filename>
<filename> (optional)

.SH DESCRIPTION
This program reads in a text file and compresses it by constructing a huffman tree and finding the bit string representations of every character.

.SH OPTIONS
.IP "inputfile outputfile"
If a second file is not specified, this program will write to standard out.

.SH AUTHOR
Eva Fineberg Ruby Boyd (Fall 2014)
 
.SH BUGS
There are no bugs in this code.
